### ISSUE TITLE
The functions computeSocialForce

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/lightsfm#3]
Hello.
There are two functions, computeSocialForce.
They are declared on lines 149 and 150 of sfm.hpp. I couldn't understand what these two functions do even after reading the code, so I would appreciate it if you could tell me what they do.

**Comment by noeperez** [comment]
Dear hatta-yuuto,

To understand the functions, first you need to read the three papers referred in the documentation.

**Comment by hatta-yuuto** [comment]
Thank you very much. I'll read the paper.
