### ISSUE TITLE
The way to get the information of the position of the agent

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/lightsfm#4]
Hello.
In the computeSocialForce function of sfm.hpp, there is a part that says "agent[i].position - agent.position" or "agent[i].position - me.position;". Where do you get the agent's position information from?
Also, what does "me" mean in the second computeSocialForce function?

**Comment by noeperez** [comment]
Hello,

this is a header-only library devised to be used from other software, which must provide the agents' information (the agents are the robot and the surrounding people). 
You were asking about social_force_window_planner, so you have a clear example about the use of this library there.

Beyond that, I must say that this package (and the related ones) is intended for people with knowledge of C++, ROS and its navigation stack. Moreover, Github issues is a tool for tracking the development of the code, indicating possible bugs and next steps in the development. So, this is not the most appropriate place for introductory explanations and guides. The required information is included in the readme pages.

**Comment by hatta-yuuto** [comment]
Thanks a lot.
