### ISSUE TITLE
Distance from Obstacles

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/lightsfm#5]
Hi.
In sfm.hpp, line 239, there is a variable called distance, but it is not outputting the correct distance to static obstacles. (It keeps outputting almost the same value even when the robot approaches the obstacle.)
On the other hand, it shows the correct distance for a pedestrian coming towards the robot.
Is this because it is not recognizing the obstacle correctly?

**Comment by noeperez** [comment]
Hello,

this is a header-only library that computes the social forces based on a list of agents whose properties must be provided externally. That means the agents' features (the obstacle distances among them, lines 115 and 116) must be filled by another "upper" software that is using this library. Therefore, the agents list, properly filled, must be passed to this library to compute the forces. 
If you are not getting correct obstacle distance values, you must check that the "upper" software is providing the obstacle distances properly. 
It is not a problem of this library for sure.

**Comment by hatta-yuuto** [comment]
Thanks a lot.
